apiVersion: v1
kind: Pod
metadata:
  name: hello-#{Octopus.Environment.Name | toLower}-pod
spec:
  containers:
    - name: hello
      image: busybox:1.28
      command: ['sh', '-c', 'echo "Hello, #{Octopus.Environment.Name}!" && sleep 3600']
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
