apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  supersecretvalue: foobar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.29.1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: nginx-configmap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-busybox-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: my-busybox
  template:
    metadata:
      labels:
        app: my-busybox
    spec:
      containers:
      - name: busybox-container
        image: docker.io/busybox:stable
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  selector:
    app: my-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort # Or ClusterIP if you don't need external access
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Hello from Nginx!</title>
    </head>
    <body>
      <h1>Good Chat from Kubernetes and ArgoCD!</h1>
    </body>
    </html>
