apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "test-app-two"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: "test-app-two"
    server: "https://kubernetes.default.svc"
  project: wait-for-argo-apps-step
  source:
    path: "ArgoCD/ApplicationManifests/test-app-two"
    repoURL: "https://github.com/tleed5/OctopusVCSTest.git"
    targetRevision: "release/test-20260424-062951"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
