apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{K8S.DeploymentName}
  namespace: #{K8S.Namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:blah
        ports:
        - containerPort: 80